// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.DbContexts;

namespace Sample.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20211216132027_d1")]
    partial class d1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sample.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Activity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfStaff")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4978846-3eec-432d-b54d-db08b75a2a83"),
                            Activity = "web developing",
                            DateTime = new DateTimeOffset(new DateTime(2021, 12, 16, 16, 50, 27, 394, DateTimeKind.Unspecified).AddTicks(2176), new TimeSpan(0, 3, 30, 0, 0)),
                            Name = "Best Company For Ever",
                            NumberOfStaff = 10
                        },
                        new
                        {
                            Id = new Guid("8702b207-d45e-4328-ae36-0216b95e19f5"),
                            Activity = "developing software",
                            DateTime = new DateTimeOffset(new DateTime(2021, 12, 16, 16, 50, 27, 397, DateTimeKind.Unspecified).AddTicks(521), new TimeSpan(0, 3, 30, 0, 0)),
                            Name = "Microsoft",
                            NumberOfStaff = 400
                        },
                        new
                        {
                            Id = new Guid("c8e7f681-fa1d-4e96-a897-d19439441e35"),
                            Activity = "Hardware Manufacturing",
                            DateTime = new DateTimeOffset(new DateTime(2021, 12, 16, 16, 50, 27, 397, DateTimeKind.Unspecified).AddTicks(574), new TimeSpan(0, 3, 30, 0, 0)),
                            Name = "Huawei",
                            NumberOfStaff = 100
                        });
                });

            modelBuilder.Entity("Sample.Entities.JobPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobPositions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b01bf89a-8125-4518-93e9-6c826b3f4d73"),
                            CompanyId = new Guid("e4978846-3eec-432d-b54d-db08b75a2a83"),
                            Degree = 1,
                            Description = ".experienced with entity frame work,.good knowledge of sql server",
                            Title = ".Net Developer"
                        },
                        new
                        {
                            Id = new Guid("c8edaad1-c78f-4034-a447-130d12a2d59e"),
                            CompanyId = new Guid("8702b207-d45e-4328-ae36-0216b95e19f5"),
                            Degree = 2,
                            Description = ".having good knowledge of IIS",
                            Title = "Dev op"
                        },
                        new
                        {
                            Id = new Guid("ce159fbb-84aa-4d8a-aaf5-ec1fb727a664"),
                            CompanyId = new Guid("8702b207-d45e-4328-ae36-0216b95e19f5"),
                            Degree = 0,
                            Description = ".Experienced with CSS3 and Html5",
                            Title = "Front End Developer"
                        });
                });

            modelBuilder.Entity("Sample.Entities.JobPosition", b =>
                {
                    b.HasOne("Sample.Entities.Company", "Company")
                        .WithMany("JobPositions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Sample.Entities.Company", b =>
                {
                    b.Navigation("JobPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
